language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t prince2208/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true  prince2208/docker-react npm run test
