language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t prince2208/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true  prince2208/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "Docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-west-2-541808310251"
  bucket_path: "Docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
